Feature/taoe cf enhancements
santiagosayshey/Profilarr pull request #59
Opened 2024-05-12 22:55 UTC by wheat4714

These changes improve the TAoE CF similar to the QxR CF changes. This smoothes out the frictions of grabs and imports.

2024-05-13 10:20 UTC, santiagosayshey requested changes

2024-05-13 10:20 UTC, santiagosayshey commented on imports/custom_formats/sonarr/custom formats (sonarr - master).json
> +                        "value": "H.265",
This needs to be changed

2024-05-18 03:23 UTC, santiagosayshey commented
@wheat4714 Just need to fix up the edge cases where a release group comes after a delimeter without taoe.

2024-05-18 03:30 UTC, santiagosayshey commented
note to myself later
- need to add radarr equiv

2024-05-18 17:58 UTC, wheat4714 commented
https://regex101.com/r/NZ0fOE/9

2024-05-18 20:17 UTC, wheat4714 reviewed
I made the changes

2024-05-18 20:20 UTC, santiagosayshey approved these changes
Approved!

2024-05-18 20:23 UTC, merged